# Unit test pipeline for PowerShell Desktop platform
# This pipeline uses the Pester test framework to
# execute unit tests for the module.
# https://aka.ms/yaml

trigger:
  - master

variables:
  TEST_OUTPUT_DIRECTORY: './test/results'
  TEST_OUTPUT_FILE: pester-testresults.xml

jobs:
- job: BuildWithTests
  displayName: 'Build and test PowerShell module'
  strategy:
    matrix:
      PowerShellDesktop:
        VM_IMAGE: 'windows-2019'
        OS_PLATFORM: 'windows'
        USE_POWERSHELL_CORE: false
      PowerShellCoreWindows:
        VM_IMAGE: 'windows-2019'
        OS_PLATFORM: 'windows'
        USE_POWERSHELL_CORE: true
      PowerShellCoreUbuntu:
        VM_IMAGE: 'ubuntu-16.04'
        OS_PLATFORM: 'ubuntu'
        USE_POWERSHELL_CORE: true
  pool:
    vmImage: $(VM_IMAGE)
  steps:
  - checkout: self
  - task: powershell@2
    displayName: 'Show current PowerShell version information'
    inputs:
      targetType: inline
      script: 'echo $PSVersionTable'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Get original Pester test framework module version'
    inputs:
      targetType: inline
      script: 'Get-Module Pester -ListAvailable'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Install Pester test framework required version'
    inputs:
      targetType: inline
      script: 'Install-Module Pester -RequiredVersion 4.6.0 -scope currentuser -force'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Get updated Pester test framework module version'
    inputs:
      targetType: inline
      script: 'Get-Module Pester -ListAvailable'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Clean build'
    inputs:
      targetType: inline
      script: './build/clean-build.ps1'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Install and configure build tools'
    inputs:
      targetType: inline
      script: './build/configure-tools.ps1 -Force -Verbose'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Install .net dependencies'
    inputs:
      targetType: inline
      script: './build/configure-tools.ps1; ./build/install.ps1'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Build module package'
    inputs:
      targetType: inline
      script: './build/configure-tools.ps1; ./build/build-package -verbose;'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Publish module for local testing'
    condition: true
    inputs:
      targetType: inline
      script: './build/configure-tools.ps1; ./build/publish-moduletodev.ps1' # Creates .devmodule directory
      pwsh: false
  - task: powershell@2
    displayName: 'Create test output directory'
    inputs:
      targetType: inline
      script: '. ./build/common-build-functions.ps1;psmkdir -name $env:TEST_OUTPUT_DIRECTORY'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Run tests'
    condition: eq(variables.OS_PLATFORM, 'windows') # Only on Windows because this hangs on Linux
    inputs:
      targetType: inline
      script: si env:TEST_OUTPUT_PATH "$($env:TEST_OUTPUT_DIRECTORY)/$($env:TEST_OUTPUT_FILE)"; ./build/import-devmodule.ps1 -initialcommand 'Invoke-Pester -OutputFile $env:TEST_OUTPUT_PATH -OutputFormat NUnitXml' -Wait -ReuseConsole
      pwsh: $(USE_POWERSHELL_CORE)
  - task: powershell@2
    displayName: 'Run tests directly'
    condition: eq(variables.OS_PLATFORM, 'ubuntu') # Only needed on Linux to avoid hangs
    inputs:
      targetType: inline
      # Include root of the repository as part of module path since it mirrors the layout
      # of the actual module (with extra files such as test files and build artifacts)
      # This is done because some tests start processes which need to load the module
      # through the module path to simulate real world scenarios
      script: 'si env:PSModulePath ($env:PSModulePath + ":" + (get-item .).fullname); Invoke-Pester -OutputFile "$($env:TEST_OUTPUT_DIRECTORY)/$($env:TEST_OUTPUT_FILE)" -OutputFormat NUnitXml'
      pwsh: $(USE_POWERSHELL_CORE)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: $(TEST_OUTPUT_DIRECTORY)/$(TEST_OUTPUT_FILE)
      failTaskOnFailedTests: true
