# Copyright 2018, Adam Edwards
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ScriptClass ScopeHelper {
    static {
        const __graphAuthScopes @(
            'Application.ReadWrite.All',
			'Application.ReadWrite.OwnedBy',
			'Bookings.Read.All',
			'Bookings.ReadWrite.Appointments',
			'Bookings.ReadWrite.All',
			'Bookings.Manage',
			'Calendars.Read',
			'Calendars.Read.Shared',
			'Calendars.ReadWrite',
			'Calendars.ReadWrite.Shared',
			'Calendars.Read',
			'Calendars.ReadWrite',
			'Contacts.Read',
			'Contacts.Read.Shared',
			'Contacts.ReadWrite',
			'Contacts.ReadWrite.Shared',
			'Contacts.Read',
			'Contacts.ReadWrite',
			'Device.Read',
			'Device.Command',
			'Device.ReadWrite.All',
			'Directory.Read.All',
			'Directory.ReadWrite.All',
			'Directory.AccessAsUser.All',
			'Directory.Read.All',
			'Directory.ReadWrite.All',
			'Files.Read',
			'Files.Read.All',
			'Files.ReadWrite',
			'Files.ReadWrite.All',
			'Files.ReadWrite.AppFolder',
			'Files.Read.Selected',
			'Files.ReadWrite.Selected',
			'Files.Read.All',
			'Files.ReadWrite.All',
			'Group.Read.All',
			'Group.ReadWrite.All',
			'Group.Read.All',
			'Group.ReadWrite.All',
			'IdentityRiskEvent.Read.All',
			'IdentityRiskEvent.Read.All',
			'IdentityProvider.Read.All',
			'IdentityProvider.ReadWrite.All',
			'DeviceManagementApps.Read.All',
			'DeviceManagementApps.ReadWrite.All',
			'DeviceManagementConfiguration.Read.All',
			'DeviceManagementConfiguration.ReadWrite.All',
			'DeviceManagementManagedDevices.PrivilegedOperations.All',
			'DeviceManagementManagedDevices.Read.All',
			'DeviceManagementManagedDevices.ReadWrite.All',
			'DeviceManagementRBAC.Read.All',
			'DeviceManagementRBAC.ReadWrite.All',
			'DeviceManagementServiceConfig.Read.All',
			'DeviceManagementServiceConfig.ReadWrite.All',
			'Mail.Read',
			'Mail.ReadWrite',
			'Mail.Read.Shared',
			'Mail.ReadWrite.Shared',
			'Mail.Send',
			'Mail.Send.Shared',
			'MailboxSettings.Read',
			'MailboxSettings.ReadWrite',
			'Mail.Read',
			'Mail.ReadWrite',
			'Mail.Send',
			'MailboxSettings.Read',
			'MailboxSettings.ReadWrite',
			'Member.Read.Hidden',
			'Member.Read.Hidden',
			'Notes.Read',
			'Notes.Create',
			'Notes.ReadWrite',
			'Notes.Read.All',
			'Notes.ReadWrite.All',
			'Notes.ReadWrite.CreatedByApp',
			'Notes.Read.All',
			'Notes.ReadWrite.All',
			'email',
			'offline_access',
			'openid',
			'profile',
			'People.Read',
			'People.Read.All',
			'People.Read.All',
			'Reports.Read.All',
			'Reports.Read.All',
			'SecurityEvents.Read.All',
			'SecurityEvents.ReadWrite.All',
			'SecurityEvents.Read.All',
			'SecurityEvents.ReadWrite.All',
			'Sites.Read.All',
			'Sites.ReadWrite.All',
			'Sites.Manage.All',
			'Sites.FullControl.All',
			'Sites.Read.All',
			'Sites.ReadWrite.All',
			'Sites.Manage.All',
			'Sites.FullControl.All',
			'Tasks.Read',
			'Tasks.Read.Shared',
			'Tasks.ReadWrite',
			'Tasks.ReadWrite.Shared',
			'Agreement.Read.All',
			'Agreement.ReadWrite.All',
			'AgreementAcceptance.Read',
			'AgreementAcceptance.Read.All',
			'User.Read',
			'User.ReadWrite',
			'User.ReadBasic.All',
			'User.Read.All',
			'User.ReadWrite.All',
			'User.Invite.All',
			'User.Export.All',
			'User.Read.All',
			'User.ReadWrite.All',
			'User.Invite.All',
			'User.Export.All',
			'User.ReadBasic.All',
			'User.Read',
			'User.Read.All',
			'User.Read',
			'Files.Read',
			'Mail.Read',
			'Calendars.Read',
			'User.Read',
			'Files.Read',
			'Sites.Read.All',
			'User.ReadWrite',
			'User.ReadWrite.All',
			'User.ReadWrite',
			'Files.ReadWrite',
			'Mail.ReadWrite',
			'Calendars.ReadWrite',
			'User.Export.All',
			'Group.Read.All',
			'Group.Read.All',
			'Group.ReadWrite.All',
			'Sites.ReadWrite.All',
			'Group.ReadWrite.All',
			'Group.ReadWrite.All',
			'UserActivity.ReadWrite.CreatedByApp'
        )

        function GetKnownScopes {
            $this.__graphAuthScopes
        }
    }
}


